function [factor_cluster_table,item_cluster_table,summary_table] = ...
    make_layer2_signed_keyitem_clusters( ...
    second_layer_table,key_item_table, ...
    min_abs_loading,min_selection,min_sign_consistency)

%% Check required variables

required_variables = { ...
    'DisplayA2', ...
    'OriginalA2', ...
    'DisplayFactor', ...
    'OriginalFactor', ...
    'Domain', ...
    'MeanLoading', ...
    'SelectionPercent', ...
    'SignConsistencyPercent', ...
    'MeanProbabilityChange'};

missing_variables = setdiff( ...
    required_variables, ...
    second_layer_table.Properties.VariableNames);

if ~isempty(missing_variables)
    error('SecondLayerTable is missing: %s', ...
        strjoin(missing_variables,', '));
end


%% Retain stable and sufficiently large Layer-2 edges

keep = ...
    abs(second_layer_table.MeanLoading) >= min_abs_loading & ...
    second_layer_table.SelectionPercent >= min_selection & ...
    second_layer_table.SignConsistencyPercent >= min_sign_consistency;

factor_cluster_table = second_layer_table(keep,:);

if isempty(factor_cluster_table)
    warning('No B2 relationships passed the selected thresholds.');

    factor_cluster_table = table;
    item_cluster_table = table;
    summary_table = table;
    return
end


%% Label relationships as positive or negative

direction = repmat("Positive",height(factor_cluster_table),1);
direction(factor_cluster_table.MeanLoading < 0) = "Negative";

factor_cluster_table = addvars( ...
    factor_cluster_table,direction, ...
    'After','OriginalA2', ...
    'NewVariableNames','Direction');

factor_cluster_table.AbsMeanLoading = ...
    abs(factor_cluster_table.MeanLoading);

factor_cluster_table = sortrows( ...
    factor_cluster_table, ...
    {'DisplayA2','Direction','AbsMeanLoading'}, ...
    {'ascend','ascend','descend'});


%% ============================================================
% Attach key-item question text to each signed A1 factor
%% ============================================================

item_cluster_table = table;

key_item_variable_names = ...
    string(key_item_table.Properties.VariableNames);

for i = 1:height(factor_cluster_table)

    display_factor = ...
        string(factor_cluster_table.DisplayFactor(i));

    original_factor = ...
        string(factor_cluster_table.OriginalFactor(i));

    %% KeyItemTable normally uses the displayed A1 factor name

    variable_position = find( ...
        key_item_variable_names == display_factor,1);

    %% Fall back to the original A1 factor name

    if isempty(variable_position)
        variable_position = find( ...
            key_item_variable_names == original_factor,1);
    end

    if isempty(variable_position)
        warning('No key-item column found for %s.',display_factor);
        continue
    end

    key_items = string( ...
        key_item_table{:,variable_position});

    key_items = strtrim(key_items);
    key_items = key_items( ...
        ~ismissing(key_items) & strlength(key_items)>0);

    if isempty(key_items)
        continue
    end

    n_items = numel(key_items);

    new_rows = table( ...
        repmat(string(factor_cluster_table.DisplayA2(i)),n_items,1), ...
        repmat(string(factor_cluster_table.OriginalA2(i)),n_items,1), ...
        repmat(string(factor_cluster_table.Direction(i)),n_items,1), ...
        repmat(display_factor,n_items,1), ...
        repmat(original_factor,n_items,1), ...
        repmat(string(factor_cluster_table.Domain(i)),n_items,1), ...
        repmat(factor_cluster_table.MeanLoading(i),n_items,1), ...
        repmat(factor_cluster_table.SelectionPercent(i),n_items,1), ...
        repmat(factor_cluster_table.SignConsistencyPercent(i),n_items,1), ...
        repmat(factor_cluster_table.MeanProbabilityChange(i),n_items,1), ...
        (1:n_items)', ...
        key_items, ...
        'VariableNames',{ ...
        'DisplayA2', ...
        'OriginalA2', ...
        'Direction', ...
        'DisplayFactor', ...
        'OriginalFactor', ...
        'Domain', ...
        'MeanB2Loading', ...
        'SelectionPercent', ...
        'SignConsistencyPercent', ...
        'MeanProbabilityChange', ...
        'KeyItemRank', ...
        'KeyItemText'});

    item_cluster_table = [item_cluster_table;new_rows];
end

if ~isempty(item_cluster_table)

    item_cluster_table.AbsMeanB2Loading = ...
        abs(item_cluster_table.MeanB2Loading);

    item_cluster_table = sortrows( ...
        item_cluster_table, ...
        {'DisplayA2','Direction', ...
         'AbsMeanB2Loading','KeyItemRank'}, ...
        {'ascend','ascend','descend','ascend'});
end


%% ============================================================
% Compact positive-versus-negative summary for each A2 factor
%% ============================================================

A2_factors = unique( ...
    string(factor_cluster_table.DisplayA2), ...
    'stable');

n_A2 = numel(A2_factors);

positive_A1_factors = strings(n_A2,1);
negative_A1_factors = strings(n_A2,1);

positive_domains = strings(n_A2,1);
negative_domains = strings(n_A2,1);

positive_key_items = strings(n_A2,1);
negative_key_items = strings(n_A2,1);

for h = 1:n_A2

    a2 = A2_factors(h);

    positive_factor_rows = ...
        string(factor_cluster_table.DisplayA2)==a2 & ...
        string(factor_cluster_table.Direction)=="Positive";

    negative_factor_rows = ...
        string(factor_cluster_table.DisplayA2)==a2 & ...
        string(factor_cluster_table.Direction)=="Negative";

    positive_A1_factors(h) = strjoin( ...
        string(factor_cluster_table.DisplayFactor( ...
        positive_factor_rows)),", ");

    negative_A1_factors(h) = strjoin( ...
        string(factor_cluster_table.DisplayFactor( ...
        negative_factor_rows)),", ");

    positive_domains(h) = strjoin( ...
        unique(string(factor_cluster_table.Domain( ...
        positive_factor_rows)),'stable'),", ");

    negative_domains(h) = strjoin( ...
        unique(string(factor_cluster_table.Domain( ...
        negative_factor_rows)),'stable'),", ");

    if ~isempty(item_cluster_table)

        positive_item_rows = ...
            string(item_cluster_table.DisplayA2)==a2 & ...
            string(item_cluster_table.Direction)=="Positive";

        negative_item_rows = ...
            string(item_cluster_table.DisplayA2)==a2 & ...
            string(item_cluster_table.Direction)=="Negative";

        positive_key_items(h) = strjoin( ...
            unique(item_cluster_table.KeyItemText( ...
            positive_item_rows),'stable')," | ");

        negative_key_items(h) = strjoin( ...
            unique(item_cluster_table.KeyItemText( ...
            negative_item_rows),'stable')," | ");
    end
end

summary_table = table( ...
    A2_factors, ...
    positive_A1_factors, ...
    negative_A1_factors, ...
    positive_domains, ...
    negative_domains, ...
    positive_key_items, ...
    negative_key_items, ...
    'VariableNames',{ ...
    'Layer2Factor', ...
    'PositiveA1Cluster', ...
    'NegativeA1Cluster', ...
    'PositiveDomains', ...
    'NegativeDomains', ...
    'PositiveKeyItems', ...
    'NegativeKeyItems'});

end