function [average_table,interpretation_table] = ...
    make_second_layer_interpretation( ...
    B2_aligned,factor_mapping,B1_reference_ids, ...
    B2_reference_ids,tol)

K1 = size(B2_aligned,1);
K2 = size(B2_aligned,2)-1;
n_runs = size(B2_aligned,3);

average_B2 = mean(B2_aligned,3);

original_A1 = "A1_" + string(B1_reference_ids(:));
display_A1 = original_A1;
domain = repmat("",K1,1);


%% Match displayed Layer-1 names and domains

if ~isempty(factor_mapping)

    mapping_original = ...
        string(factor_mapping.OriginalFactor);

    for k = 1:K1

        idx = find(mapping_original == original_A1(k),1);

        if isempty(idx)
            continue
        end

        if ismember('DisplayFactor', ...
                factor_mapping.Properties.VariableNames)

            display_A1(k) = ...
                string(factor_mapping.DisplayFactor(idx));
        end

        if ismember('Domain', ...
                factor_mapping.Properties.VariableNames)

            domain(k) = ...
                string(factor_mapping.Domain(idx));
        end
    end
end


%% Wide table of average B2 loadings

A2_original = "A2_" + string(B2_reference_ids(:));
A2_display = "Layer2_" + string((1:K2)');

variable_names = matlab.lang.makeValidName( ...
    cellstr(A2_original));

average_table = array2table( ...
    average_B2(:,2:end), ...
    'VariableNames',variable_names);

average_table = addvars( ...
    average_table, ...
    display_A1,original_A1,domain, ...
    'Before',1, ...
    'NewVariableNames', ...
    {'DisplayFactor','OriginalFactor','Domain'});


%% Long interpretation table

n_rows = K1*K2;

display_A2_column = strings(n_rows,1);
original_A2_column = strings(n_rows,1);
display_A1_column = strings(n_rows,1);
original_A1_column = strings(n_rows,1);
domain_column = strings(n_rows,1);

mean_intercept = zeros(n_rows,1);
mean_loading = zeros(n_rows,1);
sd_loading = zeros(n_rows,1);

selection_percent = zeros(n_rows,1);
positive_percent = zeros(n_rows,1);
negative_percent = zeros(n_rows,1);
sign_consistency = zeros(n_rows,1);

mean_probability_change = zeros(n_rows,1);
sd_probability_change = zeros(n_rows,1);

row = 0;

logistic = @(x) 1 ./ (1+exp(-x));

for h = 1:K2

    for k = 1:K1

        row = row+1;

        intercept_runs = reshape( ...
            B2_aligned(k,1,:),n_runs,1);

        loading_runs = reshape( ...
            B2_aligned(k,h+1,:),n_runs,1);

        probability_change_runs = ...
            logistic(intercept_runs+loading_runs) - ...
            logistic(intercept_runs);

        nonzero = abs(loading_runs) > tol;

        display_A2_column(row) = A2_display(h);
        original_A2_column(row) = A2_original(h);

        display_A1_column(row) = display_A1(k);
        original_A1_column(row) = original_A1(k);
        domain_column(row) = domain(k);

        mean_intercept(row) = mean(intercept_runs);
        mean_loading(row) = mean(loading_runs);
        sd_loading(row) = std(loading_runs);

        selection_percent(row) = 100*mean(nonzero);
        positive_percent(row) = 100*mean(loading_runs > tol);
        negative_percent(row) = 100*mean(loading_runs < -tol);

        if any(nonzero)
            sign_consistency(row) = 100*max( ...
                mean(loading_runs(nonzero) > 0), ...
                mean(loading_runs(nonzero) < 0));
        end

        mean_probability_change(row) = ...
            mean(probability_change_runs);

        sd_probability_change(row) = ...
            std(probability_change_runs);
    end
end


interpretation_table = table( ...
    display_A2_column, ...
    original_A2_column, ...
    display_A1_column, ...
    original_A1_column, ...
    domain_column, ...
    mean_intercept, ...
    mean_loading, ...
    sd_loading, ...
    selection_percent, ...
    positive_percent, ...
    negative_percent, ...
    sign_consistency, ...
    mean_probability_change, ...
    sd_probability_change, ...
    'VariableNames',{ ...
    'DisplayA2', ...
    'OriginalA2', ...
    'DisplayFactor', ...
    'OriginalFactor', ...
    'Domain', ...
    'MeanIntercept', ...
    'MeanLoading', ...
    'SDLoading', ...
    'SelectionPercent', ...
    'PositivePercent', ...
    'NegativePercent', ...
    'SignConsistencyPercent', ...
    'MeanProbabilityChange', ...
    'SDProbabilityChange'});

interpretation_table.AbsMeanLoading = ...
    abs(interpretation_table.MeanLoading);

interpretation_table = sortrows( ...
    interpretation_table, ...
    {'DisplayA2','AbsMeanLoading'}, ...
    {'ascend','descend'});

end