function question_table = ...
    make_keyitem_question_table_IPIPFMM( ...
    key_item_table,factor_mapping)

%% ============================================================
% IPIP-FFM item-code to question-text lookup
%% ============================================================

item_codes = [ ...
    "EXT1","EXT2","EXT3","EXT4","EXT5", ...
    "EXT6","EXT7","EXT8","EXT9","EXT10", ...
    "EST1","EST2","EST3","EST4","EST5", ...
    "EST6","EST7","EST8","EST9","EST10", ...
    "AGR1","AGR2","AGR3","AGR4","AGR5", ...
    "AGR6","AGR7","AGR8","AGR9","AGR10", ...
    "CSN1","CSN2","CSN3","CSN4","CSN5", ...
    "CSN6","CSN7","CSN8","CSN9","CSN10", ...
    "OPN1","OPN2","OPN3","OPN4","OPN5", ...
    "OPN6","OPN7","OPN8","OPN9","OPN10" ...
    ];

item_questions = [ ...
    "I am the life of the party.", ...
    "I don't talk a lot.", ...
    "I feel comfortable around people.", ...
    "I keep in the background.", ...
    "I start conversations.", ...
    "I have little to say.", ...
    "I talk to a lot of different people at parties.", ...
    "I don't like to draw attention to myself.", ...
    "I don't mind being the center of attention.", ...
    "I am quiet around strangers.", ...

    "I get stressed out easily.", ...
    "I am relaxed most of the time.", ...
    "I worry about things.", ...
    "I seldom feel blue.", ...
    "I am easily disturbed.", ...
    "I get upset easily.", ...
    "I change my mood a lot.", ...
    "I have frequent mood swings.", ...
    "I get irritated easily.", ...
    "I often feel blue.", ...

    "I feel little concern for others.", ...
    "I am interested in people.", ...
    "I insult people.", ...
    "I sympathize with others' feelings.", ...
    "I am not interested in other people's problems.", ...
    "I have a soft heart.", ...
    "I am not really interested in others.", ...
    "I take time out for others.", ...
    "I feel others' emotions.", ...
    "I make people feel at ease.", ...

    "I am always prepared.", ...
    "I leave my belongings around.", ...
    "I pay attention to details.", ...
    "I make a mess of things.", ...
    "I get chores done right away.", ...
    "I often forget to put things back in their proper place.", ...
    "I like order.", ...
    "I shirk my duties.", ...
    "I follow a schedule.", ...
    "I am exacting in my work.", ...

    "I have a rich vocabulary.", ...
    "I have difficulty understanding abstract ideas.", ...
    "I have a vivid imagination.", ...
    "I am not interested in abstract ideas.", ...
    "I have excellent ideas.", ...
    "I do not have a good imagination.", ...
    "I am quick to understand things.", ...
    "I use difficult words.", ...
    "I spend time reflecting on things.", ...
    "I am full of ideas." ...
    ];

item_lookup = containers.Map( ...
    cellstr(item_codes), ...
    cellstr(item_questions));


%% ============================================================
% Calculate factor consistency
%% ============================================================

n_items = height(key_item_table);
n_factors = width(key_item_table);

mean_consistency = zeros(n_factors,1);
minimum_consistency = zeros(n_factors,1);

for j = 1:n_factors

    percentages = nan(n_items,1);

    for i = 1:n_items

        current_label = string(key_item_table{i,j});

        if ismissing(current_label) || strlength(current_label)==0
            continue
        end

        token = regexp( ...
            char(current_label), ...
            '\(([\d.]+)%\)', ...
            'tokens', ...
            'once');

        if ~isempty(token)
            percentages(i) = str2double(token{1});
        end
    end

    percentages = percentages(~isnan(percentages));

    if isempty(percentages)
        mean_consistency(j) = 0;
        minimum_consistency(j) = 0;
    else
        mean_consistency(j) = mean(percentages);
        minimum_consistency(j) = min(percentages);
    end
end


%% ============================================================
% Sort factors from most to least consistent
%% ============================================================

consistency_table = table( ...
    (1:n_factors)', ...
    mean_consistency, ...
    minimum_consistency, ...
    'VariableNames',{ ...
    'OriginalColumn', ...
    'MeanConsistency', ...
    'MinimumConsistency'});

consistency_table = sortrows( ...
    consistency_table, ...
    {'MeanConsistency','MinimumConsistency'}, ...
    {'descend','descend'});

factor_order = consistency_table.OriginalColumn;

key_item_table = key_item_table(:,factor_order);


%% ============================================================
% Determine domain of each reordered factor
%% ============================================================

ordered_domains = strings(1,n_factors);

for j = 1:n_factors

    current_factor = string( ...
        key_item_table.Properties.VariableNames{j});

    mapping_position = find( ...
        string(factor_mapping.DisplayFactor) == current_factor, ...
        1);

    if isempty(mapping_position)
        ordered_domains(j) = "Unknown";
    else
        ordered_domains(j) = string( ...
            factor_mapping.Domain(mapping_position));
    end
end


%% ============================================================
% Convert item labels to full question text
%% ============================================================

question_table = key_item_table;

for j = 1:n_factors

    for i = 1:n_items

        current_label = string(key_item_table{i,j});

        if ismissing(current_label) || strlength(current_label)==0
            question_table{i,j} = "";
            continue
        end

        % Example:
        % EXT1 (100.0%)

        tokens = regexp( ...
            char(current_label), ...
            '^([A-Z]{3}\d+)\s*\(([\d.]+%)\)$', ...
            'tokens', ...
            'once');

        if isempty(tokens)
            question_table{i,j} = current_label;
            continue
        end

        item_code = string(tokens{1});
        stability_percent = string(tokens{2});

        if isKey(item_lookup,char(item_code))

            question_text = string( ...
                item_lookup(char(item_code)));

            question_table{i,j} = ...
                question_text + ...
                " [" + item_code + "] " + ...
                "(" + stability_percent + ")";

        else
            question_table{i,j} = current_label;
        end
    end
end


%% ============================================================
% Rename columns according to consistency ranking
%% ============================================================

new_variable_names = strings(1,n_factors);

for j = 1:n_factors

    new_variable_names(j) = ...
        "Factor " + string(j) + ...
        " (" + ordered_domains(j) + ")";
end

question_table.Properties.VariableNames = ...
    cellstr(new_variable_names);


%% ============================================================
% Add row names
%% ============================================================

question_table.Properties.RowNames = ...
    cellstr("Item " + string((1:n_items)'));

end