%% ============================================================
% Map IPIP-100 question codes to survey questions
%% ============================================================

question_codes = compose("q%d", 1:100);

question_text = [
    "Have a vivid imagination"
    "Hold a grudge"
    "Do not mind being the center of attention"
    "Do not like poetry"
    "Complete tasks successfully"
    "Believe that others have good intentions"
    "Avoid philosophical discussions"
    "Need a push to get started"
    "Cut others to pieces"
    "Make friends easily"
    "Feel comfortable with myself"
    "Often feel blue"
    "Am easy to satisfy"
    "Keep in the background"
    "Am always prepared"
    "Enjoy wild flights of fantasy"
    "Get stressed out easily"
    "Avoid contact with others"
    "Am not easily bothered by things"
    "Shirk my duties"
    "Can say things beautifully"
    "Suspect hidden motives in others"
    "Cheer people up"
    "Am not interested in abstract ideas"
    "Do things according to a plan"
    "Am concerned about others"
    "Am relaxed most of the time"
    "Waste my time"
    "Don't talk a lot"
    "Dislike myself"
    "Enjoy thinking about things"
    "Get back at others"
    "Warm up quickly to others"
    "Do not enjoy going to art museums"
    "Follow through with my plans"
    "Make people feel at ease"
    "Seldom feel blue"
    "Mess things up"
    "Have little to say"
    "Fear for the worst"
    "Carry the conversation to a higher level"
    "Believe that I am better than others"
    "Talk to a lot of different people at parties"
    "Tend to vote for conservative political candidates"
    "Am exacting in my work"
    "Accept people as they are"
    "Am not easily frustrated"
    "Don't put my mind on the task at hand"
    "Keep others at a distance"
    "Panic easily"
    "Tend to vote for liberal political candidates"
    "Contradict others"
    "Know how to captivate people"
    "Am not interested in theoretical discussions"
    "Make plans and stick to them"
    "Trust what people say"
    "Rarely lose my composure"
    "Leave things unfinished"
    "Don't like to draw attention to myself"
    "Worry about things"
    "Enjoy hearing new ideas"
    "Make demands on others"
    "Am the life of the party"
    "Have difficulty understanding abstract ideas"
    "Finish what I start"
    "Respect others"
    "Rarely get irritated"
    "Make a mess of things"
    "Find it difficult to approach others"
    "Have frequent mood swings"
    "Have a rich vocabulary"
    "Am out for my own personal gain"
    "Am skilled in handling social situations"
    "Do not like art"
    "Get chores done right away"
    "Sympathize with others' feelings"
    "Seldom get mad"
    "Don't see things through"
    "Retreat from others"
    "Am often down in the dumps"
    "Get excited by new ideas"
    "Have a sharp tongue"
    "Feel comfortable around people"
    "Believe that too much tax money goes to support artists"
    "Pay attention to details"
    "Have a good word for everyone"
    "Remain calm under pressure"
    "Find it difficult to get down to work"
    "Would describe my experiences as somewhat dull"
    "Am filled with doubts about things"
    "Believe in the importance of art"
    "Insult people"
    "Start conversations"
    "Rarely look for a deeper meaning in things"
    "Carry out my plans"
    "Treat all people equally"
    "Am very pleased with myself"
    "Do just enough work to get by"
    "Am hard to get to know"
    "Feel threatened easily"
];

var_mapping = table( ...
    question_codes', ...
    question_text, ...
    'VariableNames', {'Variable', 'Question'});

var_mapping.Variable = string(var_mapping.Variable);
var_mapping.Question = string(var_mapping.Question);

disp(var_mapping)